books/urls.py
from django.urls import path

from books.views import index, edit, create

urlpatterns = [
    path('', index, name='books index'),
    path('create/', create, name='create book'),
    path('edit/<int:pk>', edit, name='edit book'),
]

django101/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django102.urls')),
    path('todos/', include('todos_app.urls')),
    path('books/', include('books.urls')),
    path('profiles/', include('testing.urls')),
]

django102/models/game.py
from django.db import models

from django102.models.player import Player


class GameManager(models.Manager):
    def all_with_players_count(self):
        return self.all().annotate(players_count = models.Count('players'))


class Game(models.Model):
    objects = GameManager()

    EASY = 0
    MEDIUM = 1
    HARD = 2

    DIFICULTY_LEVELS_CHOICES = (
        (EASY, 'Easy'),
        (MEDIUM, 'Medium'),
        (HARD, 'Hard'),
    )
    name = models.CharField(max_length=30, blank=False, default='')
    level_of_difficulty = models.IntegerField(
        blank=False,
        choices=DIFICULTY_LEVELS_CHOICES,
        default=MEDIUM,
    )
    players = models.ManyToManyField(Player)

templates/games.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
    <h1>Game</h1>
    <ul>
        {% for game in object_list %}
            <li class="highlightable">
                {{ game.name }}
            </li>
        {% endfor %}
    </ul>
</body>
</html>

templates/index.html
{% extends 'shared/base.html' %}

{% load static %}

{% block page_styles %}
    <link rel="stylesheet" href="{% static 'css/css.css' %}">
{% endblock %}

{% block site_title %}
    Index page with function view
{% endblock %}

{% block site_main_content %}
    <h1>Users</h1>
    {% if users %}
        <ul>
            {% for user in users %}
                <li class="highlightable {% cycle 'even' 'odd' %}">
                    {{ user.username }}
                    {% cycle '1' '2' %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No users</p>
    {% endif %}

    <h1>Games</h1>
    {% if games %}
        <ul>
            {% for game in games %}
                <li>
                    {{ game.name }}
                    {{ game.level_of_dificulty }}
                    {{ game.get_level_of_difficulty_display }}
                    {{ game.players_count }}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No games</p>
    {% endif %}

{% endblock %}

{#{% load static %}#}
{##}
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>{{ title }}</title>#}
{#    <link rel="stylesheet" href="{% static 'css/main.css' %}">#}
{#    <script#}
{#        src="https://code.jquery.com/jquery-3.5.1.min.js"#}
{#        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTpgFtohetphbbj0="#}
{#        crossorigin="anonymous"></script>#}
{#    <script src="{% static 'js/main.js' %}">#}
{##}
{#    </script>#}
{#</head>#}
{#<body>#}

{#</body>#}
{#</html>#}

templates/index2.html
{% extends 'shared/base.html' %}

{% block site_title %}
    Index page with CBV
{% endblock %}

{% block site_main_content %}
    <h1>It works from ClassView</h1>
    {{ users }}
    {{ object_list }}
    <ul>
        {% for user in object_list %}
            <li>
                {{ user.username }}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

templates/methods_demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>It works</h1>
    <h2>{{ name }}</h2>
    <h3>{{ age }}</h3>
</body>
</html>